#!/usr/bin/env bash
# Registers the three service-account clients on a running Authorizer
# instance via the admin GraphQL API and writes .env with their credentials.
#
# Requirements: curl, python3, a running Authorizer (default http://localhost:8080).
# Usage: AUTHORIZER_ADMIN_SECRET=admin ./setup.sh
set -euo pipefail

AUTHORIZER_URL="${AUTHORIZER_URL:-http://localhost:8080}"
ADMIN_SECRET="${AUTHORIZER_ADMIN_SECRET:-admin}"
# The deployment's interactive client ID = the `aud` claim on every token.
AUTHORIZER_CLIENT_ID="${AUTHORIZER_CLIENT_ID:-kbyuFDidLLm280LIwVFiazOqjO3ty8KH}"
ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env"

if ! curl -sf -m 3 "$AUTHORIZER_URL/health" >/dev/null; then
  echo "error: Authorizer is not reachable at $AUTHORIZER_URL (start it with 'make dev')" >&2
  exit 1
fi

# create_client NAME "scope1 scope2" -> prints "client_id client_secret"
create_client() {
  local name="$1" scopes="$2"
  local scopes_json
  scopes_json=$(python3 -c 'import json,sys; print(json.dumps(sys.argv[1].split()))' "$scopes")
  # Admin GraphQL: x-authorizer-admin-secret authenticates; the Origin header
  # is required by Authorizer's CSRF guard on state-changing requests.
  local res
  res=$(curl -sf -X POST "$AUTHORIZER_URL/graphql" \
    -H 'Content-Type: application/json' \
    -H "x-authorizer-admin-secret: $ADMIN_SECRET" \
    -H "Origin: $AUTHORIZER_URL" \
    -d "$(python3 -c '
import json, sys
print(json.dumps({
  "query": "mutation($p: CreateClientRequest!){ _create_client(params:$p){ client { client_id } client_secret } }",
  "variables": {"p": {"name": sys.argv[1], "description": "with-microservices-go example", "allowed_scopes": json.loads(sys.argv[2])}},
}))' "$name" "$scopes_json")")
  python3 -c '
import json, sys
d = json.loads(sys.argv[1])
if d.get("errors"):
    sys.exit("error creating client: " + d["errors"][0]["message"])
c = d["data"]["_create_client"]
print(c["client"]["client_id"], c["client_secret"])' "$res"
}

STAMP=$(date +%s)
echo "Creating service-account clients on $AUTHORIZER_URL ..."
read -r GATEWAY_ID GATEWAY_SECRET < <(create_client "svc-gateway-$STAMP" "orders:read orders:write")
echo "  svc-gateway  -> $GATEWAY_ID  (allowed_scopes: orders:read orders:write)"
read -r ORDERS_ID ORDERS_SECRET < <(create_client "svc-orders-$STAMP" "billing:charge")
echo "  svc-orders   -> $ORDERS_ID  (allowed_scopes: billing:charge)"
read -r BILLING_ID BILLING_SECRET < <(create_client "svc-billing-$STAMP" "billing:refund")
echo "  svc-billing  -> $BILLING_ID  (allowed_scopes: billing:refund)"

cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
AUTHORIZER_URL=$AUTHORIZER_URL
AUTHORIZER_CLIENT_ID=$AUTHORIZER_CLIENT_ID
GATEWAY_PORT=4100
ORDERS_PORT=4101
BILLING_PORT=4102
ORDERS_URL=http://localhost:4101
BILLING_URL=http://localhost:4102
GATEWAY_CLIENT_ID=$GATEWAY_ID
GATEWAY_CLIENT_SECRET=$GATEWAY_SECRET
ORDERS_CLIENT_ID=$ORDERS_ID
ORDERS_CLIENT_SECRET=$ORDERS_SECRET
BILLING_CLIENT_ID=$BILLING_ID
BILLING_CLIENT_SECRET=$BILLING_SECRET
EOF

echo "Wrote $ENV_FILE"
echo "Next: 'set -a; source .env; set +a' then start the three services (see README)."
